config/routes.rb
RebelFoundation::Application.routes.draw do
  resources :users do
    put 'update_password'
  end
  match '/dashboard'        => 'users#dashboard',       as: :dashboard
  match '/forgot_password'  => 'users#forgot_password', as: :forgot_password
  match '/reset_password'   => 'users#reset_password',  as: :reset_password
  
  resource  :user_session
  match '/login'            => 'user_session#new',      as: :login
  match '/logout'           => 'user_session#destroy',  as: :logout

  # OAuth how you humor me so ...
  match '/auth/:provider/callback'  => 'user_session#create'
  match '/auth/failure'             => 'user_session#failure'

  scope controller: :pages do
    get :contact_us
    get :services
    get :portfolio
    get :about
  end
  
  root to: 'pages#index'
end

app/models/user.rb
require 'digest/sha2'

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include OmniAuth::Identity::Models::Mongoid

  field :email, type: String
  field :name, type: String
  field :password_digest, type: String
  field :token
  
  validates :email, uniqueness: true
  
  def reset_password
    self.create_token
    UserMailer.reset_password(self).deliver
  end
  
  def create_token
    self.update_attribute token, User.generate_token
  end
  
  def self.generate_token
    Digest::SHA256.hexdigest(Time.now.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_current_user
 
private
 
  def set_current_user
    return true unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
 
  def require_user
    redirect_to new_user_path unless session[:user_id]
    set_current_user
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  def new
  end

  def create
    user = User.find(request.env['omniauth.auth']['uid']) if request.env['omniauth.auth']
    if user
      session[:user_id] = user.id
      redirect_to dashboard_path, notice: 'Welcome back!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You have logged out'
  end

  def failure
    redirect_to login_path, alert: 'Invalid email or password, please try again'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, only: [:dashboard]
  def new
    @identity = env['omniauth.identity']
  end
  
  def forgot_password
    if params[:email]
      @user = User.where(email: params[:email]).first
      if @user
        @user.reset_password
      else
        redirect_to :back, alert: 'Email address not found'
      end
    end
  end
  
  def reset_password
    @user = User.where(token: params[:token]).first
  end

  def update_password
    @user = User.find params[:user_id]
    if @user.update_attributes params[:user]
      redirect_to login_path
    else
      redirect_to reset_password_path(token: @user.token), alert: 'Passwords do not match'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RebelHold | Rebel against the norm
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.logo
      = image_tag 'logo.png'
    .container-fluid
      .row-fluid
        .span2.well
          Heyo!
        .span9.well
          = yield
      .row-fluid
        %footer
          %h2
            Rebel against the Norm

app/views/pages/about.html.haml
.well.span12
  %h1
    Our Passion
  %br
    %p
      RebelHold was created to equalize the playing field for workers, providing full health care (with no co- pays), paid training, equal salaries, and to meet the physical and social needs of communities all around us. We believe that putting the means of production in the hands of the workers is a first step, and that training new people to be able to work in whatever capacity they can is valuable. Every worker is an owner, all decisions are made by consensus, and every worker has the combined responsibility of train- ing others. We are highly motivated to taking care of the needs of others through this process; and open to other processes to help.
    %br
    %h2
      Goals
    %br
      %p
        To create a mass of workers on equal grounds with each other who are taken care of completely; to pour ourselves in to improving the communities around us through training, through direct action, and through charity as needed; to communicate well with others; and to make high quality software that we can be proud of.
    %h2
      Solution
    %br 
    %p
      Us.
    %p
      We believe that through working under such equal conditions, both to us and our clients, and through such revolutionary processes as being honest with each others skill sets, teaching each other, growing in a community that seeks the most quality out of everything that we do, that we will create great software.
    %p
      Some of the tools we use to hone this process include frameworks, such as Ruby on Rails, methodologies, like Agile Development and Scrum, elastic data stores, MongoDB being our favorite, and cloud servers like Heroku. Other steps include lots of travel, a reasonable week of around 30 hours per week, and lots of pair programming; as well as constant experimentation and open source contributions.
    %p
      We are also looking for ways to build passive income in order to put us on sound financial footing out- side of client work. Some of the passive income ideas include equity in clients, software services, and applications brought to markets such as mobile marketplaces.

app/views/pages/contact_us.html.haml
.well.span12
  %h1
    Contact Us
  %br
  .row-fluid
    %h3
      Need more Information or are you ready to start?  We can be reached at:
    %br
      %p
        Phone: (480) 442-3420 or
      %p
        Email us at: riseup@rebelhold.com
      

app/views/pages/index.html.haml
.hero-unit.span12
  .row-fluid
    %p
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas aliquet faucibus. Fusce eu est eget arcu dignissim pellentesque et sagittis diam. Proin magna nibh, fermentum quis elementum in, auctor vitae arcu. In a velit sapien. Nunc iaculis molestie enim, sit amet placerat sapien molestie sit amet. Vivamus velit sapien, porttitor at semper at, aliquam nec felis. Proin mattis leo ut mi lacinia sed ultrices erat suscipit.
    %p
      Suspendisse nec faucibus sem. Etiam id metus auctor felis facilisis interdum. Nam ac ipsum malesuada tellus facilisis aliquet a quis leo. Proin ac vulputate nulla. Ut iaculis tincidunt venenatis. In hac habitasse platea dictumst. Proin commodo vehicula porta. Quisque iaculis, nibh et luctus suscipit, turpis ipsum vehicula lorem, quis congue erat dolor ac odio. Duis cursus vulputate tortor, vel volutpat lectus tempus non. Phasellus blandit accumsan velit, id blandit turpis gravida nec. Donec consequat libero quis urna euismod rhoncus. Quisque sed purus vel dui tincidunt malesuada. Suspendisse id lacus nulla. Nulla vitae diam quam. Etiam quam urna, adipiscing sit amet lacinia non, aliquam ut mi. Nunc tincidunt nulla quis purus tristique scelerisque.
    %p
      Vivamus ac vestibulum lorem. Donec euismod arcu in purus volutpat vel gravida eros vehicula. Mauris lacinia blandit sem, ac consequat enim euismod nec. Integer ornare vehicula lectus id condimentum. Aliquam faucibus pharetra nisl at pellentesque. Aliquam malesuada dapibus libero, id ullamcorper urna lobortis quis. Nullam eget ante sit amet dolor iaculis feugiat. Ut a risus quam, vitae dignissim massa. Quisque diam nunc, sodales vel pellentesque sit amet, porttitor id nulla. In elit risus, feugiat ut aliquam et, semper non tellus. Mauris facilisis ligula vitae arcu faucibus ut pharetra quam fringilla. Vivamus magna diam, tristique lobortis rutrum sit amet, ultricies vel sem. Phasellus ullamcorper, ligula ut ullamcorper commodo, nibh libero sollicitudin diam, et imperdiet tortor elit vel nibh. Donec eu mi eros, sed pulvinar erat.


    

app/views/pages/portfolio.html.haml
.well.span12
  %h1
    Our Portfolio

app/views/pages/services.html.haml
.well.span12
  %h1
    Our Services
  %br
    %h2
      Web Consulting
    %p
      We are providing web consultation at a reasonable price and with a vested interest in each client we en- gage with. Our ideal clients are making a social or just impact with their projects, seek to have a well tested project, and are open to having daily and weekly conversations over the progress of their project.
  %br
    %h2
      Web Services
    %p
      We are currently in the process of developing several web services including:
      %ul
        %li
          A Platform Independent Gaming API Service
        %li
          A Facebook Game Creation Service

app/views/user_session/new.html.haml
= form_tag '/auth/identity/callback', class: 'well form-horizontal span4' do
	= label_tag :auth_key, "Email"
	= text_field_tag :auth_key
	= label_tag :password
	= password_field_tag :password
	
	= submit_tag 'Login', class: 'btn btn-primary'
	
	= link_to 'Forgot Password', forgot_password_path, class: 'btn'

app/views/users/forgot_password.html.haml
= form_tag forgot_password_path do |f|
  = text_field_tag :email
  = submit_tag 'Reset Password'

app/views/users/new.html.haml
= form_tag '/auth/identity/register', class: 'well form-horizontal span4' do
  = label_tag :name
  = text_field_tag :name, @identity.try(:name)
  
  = label_tag :email
  = text_field_tag :email, @identity.try(:email)
  
  = label_tag :password
  = password_field_tag :password
  
  = label_tag :password_confirmation
  = password_field_tag :password_confirmation
  
  = submit_tag 'Create User', class: 'btn btn-primary'

app/views/users/reset_password.html.haml
= form_for @user, url: user_update_password_path(@user) do |f|
  = f.password_field :password
  = f.password_field :password_confirmation
  = f.submit 'Change Password'